/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity-schema.json
export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroBlock;
  impactStats?: Array<
    {
      _key: string;
    } & ImpactStat
  >;
  appeals?: Array<
    {
      _key: string;
    } & Appeal
  >;
  mission?: Mission;
  scripture?: Scripture;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  exploreCards?: Array<
    {
      _key: string;
    } & ExploreCard
  >;
  money?: MoneySplit;
  donate?: {
    monthlyTiers?: Array<
      {
        _key: string;
      } & DonateTier
    >;
    onceTiers?: Array<
      {
        _key: string;
      } & DonateTier
    >;
  };
  trust?: Trust;
};

export type Trust = {
  _type: "trust";
  registration?: string;
  statement?: string;
  partners?: Array<string>;
};

export type MoneySplit = {
  _type: "moneySplit";
  programsPct?: number;
  adminPct?: number;
  programsLabel?: string;
  adminLabel?: string;
  note?: string;
};

export type Scripture = {
  _type: "scripture";
  quote?: string;
  reference?: string;
};

export type Mission = {
  _type: "mission";
  eyebrow?: string;
  heading?: string;
  body?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  headline?: string;
  lede?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type DonateTier = {
  _type: "donateTier";
  amount?: number;
  interval?: "monthly" | "once";
  impact?: string;
};

export type ExploreCard = {
  _type: "exploreCard";
  title?: string;
  blurb?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  href?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  attribution?: string;
  placeholder?: boolean;
};

export type Appeal = {
  _type: "appeal";
  slug?: string;
  title?: string;
  blurb?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  href?: string;
  theme?: "spain" | "tanzania" | "general";
};

export type ImpactStat = {
  _type: "impactStat";
  icon?: "shower" | "home" | "heart";
  value?: string;
  label?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HomePage
  | Trust
  | MoneySplit
  | Scripture
  | Mission
  | SanityImageAssetReference
  | HeroBlock
  | DonateTier
  | ExploreCard
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | Appeal
  | ImpactStat
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/home.query.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{  hero{ eyebrow, headline, lede, image, alt },  impactStats[]{ icon, value, label },  appeals[]{ slug, title, blurb, image, alt, href, theme },  mission{ eyebrow, heading, body },  scripture{ quote, reference },  testimonials[]{ quote, attribution, placeholder },  exploreCards[]{ title, blurb, image, alt, href },  money{ programsPct, adminPct, programsLabel, adminLabel, note },  donate{    monthlyTiers[]{ amount, interval, impact },    onceTiers[]{ amount, interval, impact }  },  trust{ registration, statement, partners }}
export type HOME_QUERY_RESULT = {
  hero: {
    eyebrow: string | null;
    headline: string | null;
    lede: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
  } | null;
  impactStats: Array<{
    icon: "heart" | "home" | "shower" | null;
    value: string | null;
    label: string | null;
  }> | null;
  appeals: Array<{
    slug: string | null;
    title: string | null;
    blurb: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    href: string | null;
    theme: "general" | "spain" | "tanzania" | null;
  }> | null;
  mission: {
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
  } | null;
  scripture: {
    quote: string | null;
    reference: string | null;
  } | null;
  testimonials: Array<{
    quote: string | null;
    attribution: string | null;
    placeholder: boolean | null;
  }> | null;
  exploreCards: Array<{
    title: string | null;
    blurb: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    href: string | null;
  }> | null;
  money: {
    programsPct: number | null;
    adminPct: number | null;
    programsLabel: string | null;
    adminLabel: string | null;
    note: string | null;
  } | null;
  donate: {
    monthlyTiers: Array<{
      amount: number | null;
      interval: "monthly" | "once" | null;
      impact: string | null;
    }> | null;
    onceTiers: Array<{
      amount: number | null;
      interval: "monthly" | "once" | null;
      impact: string | null;
    }> | null;
  } | null;
  trust: {
    registration: string | null;
    statement: string | null;
    partners: Array<string> | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "homePage"][0]{\n  hero{ eyebrow, headline, lede, image, alt },\n  impactStats[]{ icon, value, label },\n  appeals[]{ slug, title, blurb, image, alt, href, theme },\n  mission{ eyebrow, heading, body },\n  scripture{ quote, reference },\n  testimonials[]{ quote, attribution, placeholder },\n  exploreCards[]{ title, blurb, image, alt, href },\n  money{ programsPct, adminPct, programsLabel, adminLabel, note },\n  donate{\n    monthlyTiers[]{ amount, interval, impact },\n    onceTiers[]{ amount, interval, impact }\n  },\n  trust{ registration, statement, partners }\n}': HOME_QUERY_RESULT;
  }
}
