/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity-schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EventItem = {
  _id: string;
  _type: "eventItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  dateLabel?: string;
  placeholder?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AppealEntry = {
  _id: string;
  _type: "appealEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  theme?: "spain" | "tanzania" | "general" | "seasonal";
  blurb?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  relatedHref?: string;
  donationDesignation?: string;
  donorboxQuery?: {
    amount?: number;
    recurring?: boolean;
    default_interval?: "m" | "y" | "o";
  };
  placeholder?: boolean;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: "tanzania" | "spain" | "general";
  excerpt?: string;
  body?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  placeholder?: boolean;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroChapter;
  philosophy?: PhilosophyChapter;
  expressions?: ExpressionsChapter;
  possible?: PossibleChapter;
  impact?: ImpactChapter;
  invitation?: InvitationChapter;
};

export type InvitationChapter = {
  _type: "invitationChapter";
  headline?: string;
  intro?: string;
  bring?: Array<string>;
  outro?: string;
  cta?: LinkCta;
};

export type ImpactChapter = {
  _type: "impactChapter";
  headline?: string;
  intro?: Array<string>;
  moments?: Array<string>;
  outro?: string;
  cta?: LinkCta;
};

export type PossibleChapter = {
  _type: "possibleChapter";
  headline?: string;
  intro?: string;
  moments?: Array<string>;
  outro?: string;
};

export type ExpressionsChapter = {
  _type: "expressionsChapter";
  headline?: string;
  intro?: string;
  credo?: Array<string>;
  rows?: Array<
    {
      _key: string;
    } & ExpressionRow
  >;
};

export type PhilosophyChapter = {
  _type: "philosophyChapter";
  headline?: string;
  body?: Array<string>;
  pullLine?: string;
};

export type HeroChapter = {
  _type: "heroChapter";
  headline?: string;
  text?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  primaryCta?: AnchorCta;
  secondaryCta?: AnchorCta;
};

export type LinkCta = {
  _type: "linkCta";
  label?: string;
  href?: string;
};

export type ExpressionRow = {
  _type: "expressionRow";
  key?: string;
  eyebrow?: string;
  heading?: string;
  belief?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  cta?: LinkCta;
};

export type AnchorCta = {
  _type: "anchorCta";
  label?: string;
  targetId?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | EventItem
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | AppealEntry
  | Story
  | HomePage
  | InvitationChapter
  | ImpactChapter
  | PossibleChapter
  | ExpressionsChapter
  | PhilosophyChapter
  | HeroChapter
  | LinkCta
  | ExpressionRow
  | AnchorCta
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/appeals.query.ts
// Variable: APPEALS_QUERY
// Query: *[_type == "appealEntry"] | order(_createdAt asc){  slug,  title,  theme,  blurb,  body,  image,  alt,  relatedHref,  donationDesignation,  donorboxQuery{ amount, recurring, default_interval },  placeholder}
export type APPEALS_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  theme: "general" | "seasonal" | "spain" | "tanzania" | null;
  blurb: string | null;
  body: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  alt: string | null;
  relatedHref: string | null;
  donationDesignation: string | null;
  donorboxQuery: {
    amount: number | null;
    recurring: boolean | null;
    default_interval: "m" | "o" | "y" | null;
  } | null;
  placeholder: boolean | null;
}>;

// Source: lib/sanity/events.query.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "eventItem"] | order(date asc, _createdAt asc){  slug,  title,  summary,  image,  alt,  dateLabel,  placeholder}
export type EVENTS_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  summary: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  alt: string | null;
  dateLabel: string | null;
  placeholder: boolean | null;
}>;

// Source: lib/sanity/home.query.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{  hero{ headline, text, image, alt, primaryCta{ label, targetId }, secondaryCta{ label, targetId } },  philosophy{ headline, body, pullLine },  expressions{ headline, intro, credo, rows[]{ key, eyebrow, heading, belief, body, image, alt, cta{ label, href } } },  possible{ headline, intro, moments, outro },  impact{ headline, intro, moments, outro, cta{ label, href } },  invitation{ headline, intro, bring, outro, cta{ label, href } }}
export type HOME_QUERY_RESULT = {
  hero: {
    headline: string | null;
    text: Array<string> | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    primaryCta: {
      label: string | null;
      targetId: string | null;
    } | null;
    secondaryCta: {
      label: string | null;
      targetId: string | null;
    } | null;
  } | null;
  philosophy: {
    headline: string | null;
    body: Array<string> | null;
    pullLine: string | null;
  } | null;
  expressions: {
    headline: string | null;
    intro: string | null;
    credo: Array<string> | null;
    rows: Array<{
      key: string | null;
      eyebrow: string | null;
      heading: string | null;
      belief: string | null;
      body: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      alt: string | null;
      cta: {
        label: string | null;
        href: string | null;
      } | null;
    }> | null;
  } | null;
  possible: {
    headline: string | null;
    intro: string | null;
    moments: Array<string> | null;
    outro: string | null;
  } | null;
  impact: {
    headline: string | null;
    intro: Array<string> | null;
    moments: Array<string> | null;
    outro: string | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  invitation: {
    headline: string | null;
    intro: string | null;
    bring: Array<string> | null;
    outro: string | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
} | null;

// Source: lib/sanity/stories.query.ts
// Variable: STORIES_QUERY
// Query: *[_type == "story"] | order(_createdAt asc){  slug,  title,  location,  excerpt,  body,  images[]{ ..., asset },  placeholder}
export type STORIES_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  location: "general" | "spain" | "tanzania" | null;
  excerpt: string | null;
  body: string | null;
  images: Array<{
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  placeholder: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "appealEntry"] | order(_createdAt asc){\n  slug,\n  title,\n  theme,\n  blurb,\n  body,\n  image,\n  alt,\n  relatedHref,\n  donationDesignation,\n  donorboxQuery{ amount, recurring, default_interval },\n  placeholder\n}': APPEALS_QUERY_RESULT;
    '*[_type == "eventItem"] | order(date asc, _createdAt asc){\n  slug,\n  title,\n  summary,\n  image,\n  alt,\n  dateLabel,\n  placeholder\n}': EVENTS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  hero{ headline, text, image, alt, primaryCta{ label, targetId }, secondaryCta{ label, targetId } },\n  philosophy{ headline, body, pullLine },\n  expressions{ headline, intro, credo, rows[]{ key, eyebrow, heading, belief, body, image, alt, cta{ label, href } } },\n  possible{ headline, intro, moments, outro },\n  impact{ headline, intro, moments, outro, cta{ label, href } },\n  invitation{ headline, intro, bring, outro, cta{ label, href } }\n}': HOME_QUERY_RESULT;
    '*[_type == "story"] | order(_createdAt asc){\n  slug,\n  title,\n  location,\n  excerpt,\n  body,\n  images[]{ ..., asset },\n  placeholder\n}': STORIES_QUERY_RESULT;
  }
}
