/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity-schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EventItem = {
  _id: string;
  _type: "eventItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  dateLabel?: string;
  placeholder?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AppealEntry = {
  _id: string;
  _type: "appealEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  theme?: "spain" | "tanzania" | "general" | "seasonal";
  blurb?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  relatedHref?: string;
  donationDesignation?: string;
  donorboxQuery?: {
    amount?: number;
    recurring?: boolean;
    default_interval?: "m" | "y" | "o";
  };
  placeholder?: boolean;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: "tanzania" | "spain" | "general";
  excerpt?: string;
  body?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  placeholder?: boolean;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HomeHero;
  philosophy?: HomePhilosophy;
  expressions?: HomeExpressions;
  via?: HomeVia;
  impact?: HomeImpact;
  stories?: HomeStories;
  impactCta?: HomeImpactCta;
  partners?: HomePartners;
  closing?: HomeClosing;
};

export type HomeClosing = {
  _type: "homeClosing";
  eyebrow?: string;
  heading?: SplitHeading;
  body?: string;
  primaryCta?: LinkCta;
  secondaryCta?: LinkCta;
};

export type HomePartners = {
  _type: "homePartners";
  label?: string;
  marks?: Array<
    {
      _key: string;
    } & PartnerMark
  >;
  logoSlot?: LinkCta;
};

export type HomeImpactCta = {
  _type: "homeImpactCta";
  eyebrow?: string;
  heading?: SplitHeading;
  cta?: LinkCta;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type HomeStories = {
  _type: "homeStories";
  eyebrow?: string;
  heading?: SplitHeading;
  viewAll?: LinkCta;
  feature?: StoryCard;
  cards?: Array<
    {
      _key: string;
    } & StoryCard
  >;
};

export type HomeImpact = {
  _type: "homeImpact";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  stats?: Array<
    {
      _key: string;
    } & ImpactStat
  >;
};

export type HomeVia = {
  _type: "homeVia";
  eyebrow?: string;
  heading?: SplitHeading;
  body?: string;
  cta?: LinkCta;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type HomeExpressions = {
  _type: "homeExpressions";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  cards?: Array<
    {
      _key: string;
    } & ExpressionCard
  >;
};

export type HomePhilosophy = {
  _type: "homePhilosophy";
  eyebrow?: string;
  heading?: SplitHeading;
  body?: string;
  pullquote?: string;
};

export type HomeHero = {
  _type: "homeHero";
  eyebrow?: string;
  heading?: SplitHeading;
  lede?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  primaryCta?: LinkCta;
  secondaryCta?: LinkCta;
};

export type LinkCta = {
  _type: "linkCta";
  label?: string;
  href?: string;
};

export type SplitHeading = {
  _type: "splitHeading";
  lead?: string;
  accent?: string;
};

export type PartnerMark = {
  _type: "partnerMark";
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type StoryCard = {
  _type: "storyCard";
  title?: string;
  blurb?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  href?: string;
};

export type ImpactStat = {
  _type: "impactStat";
  key?: string;
  value?: number;
  suffix?: string;
  label?: string;
};

export type ExpressionCard = {
  _type: "expressionCard";
  key?: string;
  index?: string;
  title?: string;
  tagline?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  cta?: LinkCta;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | EventItem
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | AppealEntry
  | Story
  | HomePage
  | HomeClosing
  | HomePartners
  | HomeImpactCta
  | HomeStories
  | HomeImpact
  | HomeVia
  | HomeExpressions
  | HomePhilosophy
  | HomeHero
  | LinkCta
  | SplitHeading
  | PartnerMark
  | StoryCard
  | ImpactStat
  | ExpressionCard
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/appeals.query.ts
// Variable: APPEALS_QUERY
// Query: *[_type == "appealEntry"] | order(_createdAt asc){  slug,  title,  theme,  blurb,  body,  image,  alt,  relatedHref,  donationDesignation,  donorboxQuery{ amount, recurring, default_interval },  placeholder}
export type APPEALS_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  theme: "general" | "seasonal" | "spain" | "tanzania" | null;
  blurb: string | null;
  body: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  alt: string | null;
  relatedHref: string | null;
  donationDesignation: string | null;
  donorboxQuery: {
    amount: number | null;
    recurring: boolean | null;
    default_interval: "m" | "o" | "y" | null;
  } | null;
  placeholder: boolean | null;
}>;

// Source: lib/sanity/events.query.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "eventItem"] | order(date asc, _createdAt asc){  slug,  title,  summary,  image,  alt,  dateLabel,  placeholder}
export type EVENTS_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  summary: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  alt: string | null;
  dateLabel: string | null;
  placeholder: boolean | null;
}>;

// Source: lib/sanity/home.query.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{  hero{ eyebrow, heading{ lead, accent }, lede, image, alt, primaryCta{ label, href }, secondaryCta{ label, href } },  philosophy{ eyebrow, heading{ lead, accent }, body, pullquote },  expressions{ eyebrow, heading, intro, cards[]{ key, index, title, tagline, body, image, alt, cta{ label, href } } },  via{ eyebrow, heading{ lead, accent }, body, cta{ label, href }, image, alt },  impact{ eyebrow, heading, intro, stats[]{ key, value, suffix, label } },  stories{ eyebrow, heading{ lead, accent }, viewAll{ label, href }, feature{ title, blurb, image, alt, href }, cards[]{ title, blurb, image, alt, href } },  impactCta{ eyebrow, heading{ lead, accent }, cta{ label, href }, image, alt },  partners{ label, marks[]{ name, logo }, logoSlot{ label, href } },  closing{ eyebrow, heading{ lead, accent }, body, primaryCta{ label, href }, secondaryCta{ label, href } }}
export type HOME_QUERY_RESULT = {
  hero: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    lede: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    primaryCta: {
      label: string | null;
      href: string | null;
    } | null;
    secondaryCta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  philosophy: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    body: string | null;
    pullquote: string | null;
  } | null;
  expressions: {
    eyebrow: string | null;
    heading: string | null;
    intro: string | null;
    cards: Array<{
      key: string | null;
      index: string | null;
      title: string | null;
      tagline: string | null;
      body: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      alt: string | null;
      cta: {
        label: string | null;
        href: string | null;
      } | null;
    }> | null;
  } | null;
  via: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    body: string | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
  } | null;
  impact: {
    eyebrow: string | null;
    heading: string | null;
    intro: string | null;
    stats: Array<{
      key: string | null;
      value: number | null;
      suffix: string | null;
      label: string | null;
    }> | null;
  } | null;
  stories: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    viewAll: {
      label: string | null;
      href: string | null;
    } | null;
    feature: {
      title: string | null;
      blurb: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      alt: string | null;
      href: string | null;
    } | null;
    cards: Array<{
      title: string | null;
      blurb: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      alt: string | null;
      href: string | null;
    }> | null;
  } | null;
  impactCta: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
  } | null;
  partners: {
    label: string | null;
    marks: Array<{
      name: string | null;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    logoSlot: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  closing: {
    eyebrow: string | null;
    heading: {
      lead: string | null;
      accent: string | null;
    } | null;
    body: string | null;
    primaryCta: {
      label: string | null;
      href: string | null;
    } | null;
    secondaryCta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
} | null;

// Source: lib/sanity/stories.query.ts
// Variable: STORIES_QUERY
// Query: *[_type == "story"] | order(_createdAt asc){  slug,  title,  location,  excerpt,  body,  images[]{ ..., asset },  placeholder}
export type STORIES_QUERY_RESULT = Array<{
  slug: Slug | null;
  title: string | null;
  location: "general" | "spain" | "tanzania" | null;
  excerpt: string | null;
  body: string | null;
  images: Array<{
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  placeholder: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "appealEntry"] | order(_createdAt asc){\n  slug,\n  title,\n  theme,\n  blurb,\n  body,\n  image,\n  alt,\n  relatedHref,\n  donationDesignation,\n  donorboxQuery{ amount, recurring, default_interval },\n  placeholder\n}': APPEALS_QUERY_RESULT;
    '*[_type == "eventItem"] | order(date asc, _createdAt asc){\n  slug,\n  title,\n  summary,\n  image,\n  alt,\n  dateLabel,\n  placeholder\n}': EVENTS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  hero{ eyebrow, heading{ lead, accent }, lede, image, alt, primaryCta{ label, href }, secondaryCta{ label, href } },\n  philosophy{ eyebrow, heading{ lead, accent }, body, pullquote },\n  expressions{ eyebrow, heading, intro, cards[]{ key, index, title, tagline, body, image, alt, cta{ label, href } } },\n  via{ eyebrow, heading{ lead, accent }, body, cta{ label, href }, image, alt },\n  impact{ eyebrow, heading, intro, stats[]{ key, value, suffix, label } },\n  stories{ eyebrow, heading{ lead, accent }, viewAll{ label, href }, feature{ title, blurb, image, alt, href }, cards[]{ title, blurb, image, alt, href } },\n  impactCta{ eyebrow, heading{ lead, accent }, cta{ label, href }, image, alt },\n  partners{ label, marks[]{ name, logo }, logoSlot{ label, href } },\n  closing{ eyebrow, heading{ lead, accent }, body, primaryCta{ label, href }, secondaryCta{ label, href } }\n}': HOME_QUERY_RESULT;
    '*[_type == "story"] | order(_createdAt asc){\n  slug,\n  title,\n  location,\n  excerpt,\n  body,\n  images[]{ ..., asset },\n  placeholder\n}': STORIES_QUERY_RESULT;
  }
}
