import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
await p.goto('http://localhost:3000/en', { waitUntil: 'domcontentloaded' })
const el = p.locator('section', { hasText: 'The difference your support makes' }).first()
await el.scrollIntoViewIfNeeded()
await p.waitForTimeout(400)
await el.screenshot({ path: '.firecrawl/cc-impact.png' })
await b.close()
console.log('done')
